### PR TITLE
Support both runtimes: tokio & actix

### PR DESCRIPTION
**Pull request by tworec**
I'm using mostly `actix_rt` in my tests so I've added support for it while still supporting `tokio`.

User can wrap test fn manually with reactor of choice:

```
#[tokio::test]
#[serial]
async fn test_async_can_return() -> Result<(), ()> {
    init();
    Ok(())
}

#[actix_rt::test]
#[serial]
async fn test_async_can_return_actix() -> Result<(), ()> {
    init();
    Ok(())
}
```

When not wrapped `actix_rt` reactor code will be generated.
```
#[serial]
async fn test_async() {
    init();
}
```

But user can also pick up favourite reactor via `serial(...)` annotation arg as shown below
```
#[serial({actix_rt})]
async fn test_async_actix_rt() {
    init();
}

#[serial(key{actix_rt})]
async fn test_async_key_actix_rt() {
    init();
}
```

### CODE REVIEW

**Comment by tworec** [comment]
I'm not resolving conflicts bc I want to hear from you abut the idea first.

**Comment by palfrey** [comment]
> I'm not resolving conflicts bc I want to hear from you abut the idea first.

So I'm trying to understand what this adds. AFAIK, you can still happily use either reactor (or other ones like [smol](https://github.com/smol-rs/smol)), just you have to add the explicit `#[<reactor name>::test]` on every test, and this means that you don't have to do that? Are there any scenarios where the reactor test attribute isn't enough with the current setup and you need additional things in the `serial_test` wrappers to support a particular reactor?

**Comment by tworec** [comment]
> So I'm trying to understand what this adds. AFAIK, you can still happily use either reactor (or other ones like [smol](https://github.com/smol-rs/smol)), just you have to add the explicit `#[<reactor name>::test]` on every test, and this means that you don't have to do that?

Ok, good point, I should have stated clearly in the description, what issue I'm trying to overcome here.

>  Are there any scenarios where the reactor test attribute isn't enough with the current setup and you need additional things in the `serial_test` wrappers to support a particular reactor?


If one is using two explicit procedural macros on single test, like this:

```
#[actix_rt::test]
#[serial]
async fn test_sth...
```

and there is a compile error then the compiler is unable to point out the line which caused the error.
It applies also to reverted order ie. `#[serial]` at the top.
This is very cumbersome and slows down development much.
So I've come out with generating reactor code within serial_test itself.
This is kinda workaround, but I'm using it with success within our project: https://github.com/golemfactory/yagna

**Comment by palfrey** [comment]
> and there is a compile error then the compiler is unable to point out the line which caused the error.

I'm not able to demo this. My test code was 

```
    #[actix_rt::test]
    #[serial]
    async fn test_async_serial_no_arg_actix() {
        init();
        wrong
    }
```
and it complains at the "wrong" text just fine.

> It applies also to reverted order ie. `#[serial]` at the top.

Yeah, that one is annoying, and worth adding in a feature to go "hey you've got a `test` or `something::test` before serial, this is probably bad", rather than the current "it breaks inside the macro". I'm going to try digging around in the code you've got here and fish out just that feature for a new PR.

So far I'm not pro the internal reactor option, partially because although actix and tokio are the big players in all of this there are other options (and I really don't want to have to be asked to support every little runtime that someone comes up with), but also because it feels fairly "magic" to me i.e. the current `serial` attribute is fairly easy to understand what it does, and the current combination with external reactor attributes is reasonably clear what it means (even if you need to do things in a particular sequence). I'd like to maintain that pattern ideally, while maybe putting in a few more guardrails to warn against bad combinations of things.

**Comment by palfrey** [comment]
> Yeah, that one is annoying, and worth adding in a feature to go "hey you've got a `test` or `something::test` before serial, this is probably bad", rather than the current "it breaks inside the macro". I'm going to try digging around in the code you've got here and fish out just that feature for a new PR.

https://github.com/palfrey/serial_test/pull/36 does this. Thoughts?

**Comment by palfrey** [comment]
As there's been no activity here for over a month, I'm closing it for the moment. Feel free to reopen if you've got any thoughts on the above items.

**Comment by tworec** [comment]
> > and there is a compile error then the compiler is unable to point out the line which caused the error.
> 
> I'm not able to demo this. My test code was

You cannot reproduce it anymore because the rust team has fixed it within 1.49.0 so much before I've posted this PR, but I haven't checked it back then. Sorry for this.

I've downgraded rust to 1.48.0 to see it

```rust
#[actix_rt::test]
#[serial_test::serial]
async fn test_async_serial_compile_error() {
    println!("{}", 1);
    wrong_with_serial
}

#[actix_rt::test]
async fn test_async_compile_error() {
    println!("{}", 2);
    wrong_without_serial
}
```
yields
```
error[E0425]: cannot find value `wrong_with_serial` in this scope

error[E0425]: cannot find value `wrong_without_serial` in this scope
  --> tests/test_serial_test_ux.rs:11:5
   |
11 |     wrong_without_serial
   |     ^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

I saw your code within #36 and it seems like it is a good side effect of our discussion here. Nice to see, that something good arisen from this discussion :)

**Pull request closed without merging**
