### PR TITLE
Make logging with log a default feature

### PR DESCRIPTION
**Pull request by erik1p**
This change makes logging with the `log` crate a (default) feature but otherwise allows it, and the crate dependency, to be opted-out of by upstream consumers.

### CODE REVIEW

**Comment by erik1p** [comment]
We don't allow using the log crate to steer internal developers toward our internal logging APIs which are hardened against leaking PII and secrets.

I'm hoping I can use your crate for some of my tests of interactions with global and/or mutually exclusive resources. There is one `debug!(...)` macro sinking my sink RN.

**Comment by palfrey** [comment]
Thanks for this. I've just added https://github.com/palfrey/serial_test/pull/63 to explicitly test with no default features which wasn't needed until now, but now there's a default feature here it's good to check that. If you could merge `main` into this just to double-check stuff, and then we can get this merged.

On a personal note I'm glad to see this potentially used by 1Password as myself and my spouse have been using your product for a few years now and we're happy users of it :)

**Comment by erik1p** [comment]
I'm using it to test our crash reporting crate. I just overhauled it and added more testing around how it maintains its local crash report storage.

Glad to hear you love the app <3 Have you seen https://github.com/1Password/1password-teams-open-source ? I appreciate the work you and other contributors put into making the rust community as great as it is.

**Comment by palfrey** [comment]
> Glad to hear you love the app <3 Have you seen https://github.com/1Password/1password-teams-open-source ? I appreciate the work you and other contributors put into making the rust community as great as it is.

Thanks. I hadn't seen that before. The Teams offer is generous, but doesn't quite cover what would actually be useful to me (a free Families account), so I've [filed a bug about that](https://github.com/1Password/1password-teams-open-source/issues/555)

**Comment by palfrey** [comment]
FYI, 0.8.0 just got released with this and [a couple of other features](https://github.com/palfrey/serial_test/releases/tag/v0.8.0)

**Pull request merged**
