### PR TITLE
proc-macro2 version update- has other dependencies version updates

### PR DESCRIPTION
**Pull request by vsirivol**
Dependencies version updates to address: https://github.com/palfrey/serial_test/issues/116

### CODE REVIEW

**Comment by palfrey** [comment]
Given this doesn't actually change any part of the `Cargo.toml` only the lock file, I'm not entirely seeing the usefulness of this PR given only the former feed into the actual published crate.

Now, what would be of interest is a new build step like the "minimal versions" one, but starting with a `cargo update` to confirm we're still compatible with the bleeding edge of our listed dependencies i.e so people can do things like this update in their builds and show it'll still work fine, given we already do a monthly build check.

**Comment by vsirivol** [comment]
> Given this doesn't actually change any part of the `Cargo.toml` only the lock file, I'm not entirely seeing the usefulness of this PR given only the former feed into the actual published crate.

> Now, what would be of interest is a new build step like the "minimal versions" one, but starting with a `cargo update` to confirm we're still compatible with the bleeding edge of our listed dependencies i.e so people can do things like this update in their builds and show it'll still work fine, given we already do a monthly build check.

I have added a workflow step to update the packages.

**Comment by palfrey** [comment]
Thanks. So I ended up also wanting some build steps (and to run on stable), and then also realising that the `env_logger` requirements could be reduced, etc, etc. https://github.com/palfrey/serial_test/pull/118 builds on this and adds the extra bits I wanted for this which was a better path than trying to micromanage this with the features I wanted :)

**Comment by vsirivol** [comment]
Thanks for adding that. I am not sure if I am missing something but Cargo.lock file is not updated with the latest versions. Addressed the changes needed https://github.com/palfrey/serial_test/pull/118

**Pull request closed without merging**
